### ISSUE TITLE
Could it be that large cookies are not displayed in the response?

### ISSUE THREAD

**Issue by workmichsem** [basdijkstra/rest-assured-net#90] opened 2023-06-26 07:11 UTC
Hello
I had such a problem

I am running a post query:
`https://site.com/login/Authenticate.bam?email=login@email.com&password=pass`

It returns multiple cookies in the response.
```
Set-Cookie: 
Id=118547; path=/; 
secure, _CSRFCOOKIE=a6ad9354-6c83-9572-9b8a-4e3d71eb8d48; path=/; 
secure, PeriodId=118547; path=/; secure
```

But it doesn't return one long cookie. In postman the response will look like this
```
Id=118547;
_CSRFCOOKIE=a6ad9354-6c83-9572-9b8a-4e3d71eb8d48; 
PeriodId=118547; 
Auth=CE0B9D9E8AC0EDC39F07A852963233EB0848B9334FD64B1761E04EEAFF40E8DE627F521CAA38B5BAC865EE9ED684C307E2CB9B2405A2828F20160051F2146ECBB0C8B27A811E06AD5E77FC24FB5F4D3CD9BEA478BAEF53235EC0EED9BC446D60A343C692458695FA29AE974E8BDC7C7A65258B1C8FA7C57AFB09CF4A4CDE45E58D2B6945CB840EACF1CFA4829B9C48D912A55448CC6DF8B17C3139618039ECC30007B013;
```

**Comment by basdijkstra** [comment] 2023-06-26 07:40
Hey @workmichsem, is this purely a problem with printing the response cookies?

Because I currently don't have specific logic for printing multivalue cookies, or for multivalue headers in general.

Also, is that `Auth` value in your example a cookie or a 'normal' header? Because it's only in the second example, not in the first.

**Comment by workmichsem** [comment] 2023-06-26 07:48
@basdijkstra 
Now I've only encountered this with cookies

I think you're right, this is not a 'normal' header.
However, for example, Google Chrome displays this Auth as a normal cookie.
Postman does not display Auth in headers, but displays in cookies

**Comment by basdijkstra** [comment] 2023-06-26 08:00
@workmichsem got it. And when you say 'are not displayed in the response' do you mean you don't see them when you're logging the response (but they are still in the response) or are they not in the response at all?

**Comment by workmichsem** [comment] 2023-06-26 08:07
@basdijkstra  I use
```
 ClientV1
 .Login(query)
 .Log(ResponseLogLevel.All);
```
And I don't see this Auth

**Comment by workmichsem** [comment] 2023-06-26 08:08
If I use .Extract().Response(); it does not working

**Comment by basdijkstra** [comment] 2023-06-26 08:11
> @basdijkstra I use
> 
> ```
>  ClientV1
>  .Login(query)
>  .Log(ResponseLogLevel.All);
> ```
> 
> And I don't see this Auth

Got it. I'll see if I can make it print multi-value cookies and headers in a better way.

> If I use .Extract().Response(); it does not working

What does not work? `Extract()` is for storing (parts of) the response in an object (in this case an `HttpResponseMessage`), not for printing.

**Comment by workmichsem** [comment] 2023-06-26 08:18
Sorry
I meant .Extract().Response().Headers;
I assumed that this cookie would be in the headers.
And perhaps the full logging of the response did not show it.
But like you said, this is not a regular cookie header.

**Comment by basdijkstra** [comment] 2023-06-26 08:21
No worries. Would it be possible to have a quick call so that you can show me what you mean and what you see in Postman for example? That would make things a lot easier for me :)

I can send you a Teams link if you send your email address to bas@ontestautomation.com

**Comment by workmichsem** [comment] 2023-06-26 08:33
I can't show anything due to NDA
But I can show screenshots
This is what the response looks like in postman
![1](https://github.com/basdijkstra/rest-assured-net/assets/51508014/ea2523a3-fbfa-4c6e-b278-0bdc8d1f4f7e)
![2](https://github.com/basdijkstra/rest-assured-net/assets/51508014/83ac70fe-232a-44cd-81aa-b0e625b99752)

**Comment by basdijkstra** [comment] 2023-06-26 08:35
No problem. Thanks, that's already very helpful. I'll get to work. Don't know exactly when but I'll try and spend some time on this soon.

**Comment by workmichsem** [comment] 2023-06-26 08:37
Thank you very much!

**Comment by workmichsem** [comment] 2023-06-27 03:47
In your example, Auth is passed from the server as a "normal" cookie or "file"?

**Comment by basdijkstra** [comment] 2023-06-27 04:05
That’s a ‘normal’ cookie I guess, as I create it by passing a ‘Set-Cookie’ response header.

**Comment by workmichsem** [comment] 2023-06-29 03:46
Did you manage to somehow move forward with these non-ordinary cookies?

**Comment by basdijkstra** [comment] 2023-06-29 04:36
Not yet, but I’ll have another good look in the next couple of days.

**Comment by workmichsem** [comment] 2023-06-29 05:33
My resourse is comletely closed and no there is no way to give access

**Comment by basdijkstra** [comment] 2023-06-29 05:36
I understand that :) I’ll see if I can find a public example, without something like that it’s going to be difficult to understand what exactly I’m looking for.

**Comment by basdijkstra** [comment] 2023-06-29 18:36
So, the only difference between the `Auth` cookie and the other ones in your example is that it's `HttpOnly`, [a way to restrict access to cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies).

The problem here is that when I add a cookie in my stub response like this:

```csharp
this.Server?.Given(Request.Create().WithPath("/response-with-cookies").UsingGet())
                .RespondWith(Response.Create()
                .WithStatusCode(200)
                .WithHeader("Set-Cookie", "Auth=supersecret; HttpOnly")
                .WithHeader("Content-Type", "text/plain"));
```

and then inspect the `CookieCollection` of the `HttpHandler` I use to send the request and print some details about the cookie:

```csharp
Console.WriteLine($"COOKIES: {this.handler.CookieContainer.Count}");
var cookieEnum = this.handler.CookieContainer.GetCookies(new Uri("http://localhost:9876/response-with-cookies")).GetEnumerator();
cookieEnum.MoveNext();
Cookie cookie = (Cookie)cookieEnum.Current;
Console.WriteLine($"NAME: {cookie!.Name}");
Console.WriteLine($"HTTPONLY: {cookie!.HttpOnly}");

I see this:

```
COOKIES: 1
NAME: Auth
HTTPONLY: True
```

so I know I set the cookie to `HttpOnly` successfully. If I then print the response, I _do_ see the cookie:

`Set-Cookie: Auth=supersecret; HttpOnly`

I'm out of options here at the moment. Unless I find a way to reproduce or at least have a look at what you see on your end, there's no way I can address this issue at the moment, @workmichsem.

**Comment by workmichsem** [comment] 2023-06-30 11:30
I know that this cookie is generated by the method
FormsAuthentication.GetAuthCookie()
It is in .NET 4.8

**Comment by workmichsem** [comment] 2023-06-30 11:38
Also this cookie comes with the global domain "site.com"
The rest come from "level.site.com"

**Comment by basdijkstra** [comment] 2023-06-30 13:07
> Also this cookie comes with the global domain "site.com" The rest come from "level.site.com"

I don't think that matters here:

![image](https://github.com/basdijkstra/rest-assured-net/assets/10740451/712e9414-05aa-479d-8d96-d793330e8177)

**Comment by basdijkstra** [comment] 2023-06-30 13:08
> I know that this cookie is generated by the method FormsAuthentication.GetAuthCookie() It is in .NET 4.8

I don't think that the code that generates a cookie matters much. A cookie is a cookie.

**Comment by basdijkstra** [comment] 2023-06-30 13:28
Hmm.. If I make the cookie I add both `secure` and `httponly`, what I described above does not work anymore, i.e., the cookie is not accessible, and that's probably also why it isn't printed when logging the response.

How big of a problem is this, @workmichsem? Because I'm not even sure I can access this cookie, and if I can I'll need to store it somewhere in case someone wants to maybe print it..

**Comment by workmichsem** [comment] 2023-07-03 04:17
This is an authorization cookie that is generated by the built-in libraries. For one of my projects, this is critical because without a token there will be no access to other APIs

Of course, this way of generating a token allows me to generate it myself, since I know what data is sent to it on the backend side
But then I need to switch to .NET 4.8 in which these half of my libraries that I use will not work

I could make an EXE with .NET 4.8 and FormsAuthentication.GetAuthCookie() method. And then call it in the code to generate cookies on my side.
But I would not like to use this method.

**Comment by basdijkstra** [comment] 2023-07-03 07:52
Ah OK I misunderstood then, you _don't_ just want me to print them, you want to be able to access cookies that are both `secure` and `httponly` (because I think that's where the problem is).

OK, let me see what I can do.

**Comment by workmichsem** [comment] 2023-07-03 08:15
All I need is for AUTH to be extracted from the response.
So that I can use the received AUTH in other requests

It will be very cool if you can do it

**Comment by basdijkstra** [comment] 2023-07-03 11:04
@workmichsem, what .NET version are you using with RestAssured.Net?

Because I think there might be a solution here, but that requires dropping support for .NET Core 3.1 (which I intend to do anyways at some point).

What I can do is build out that solution and publish that as an alpha version for you to test it, because I want to know if it works for you. How does that sound?

But again, please keep in mind that it won't work with .NET Core 3.1.

**Comment by workmichsem** [comment] 2023-07-03 11:34
I am using .NET 6

It will be sufficient for me to be able to extract such AUTH from the response

**Comment by basdijkstra** [comment] 2023-07-03 13:12
@workmichsem can you please install version `3.0.0-beta.cookies` (https://www.nuget.org/packages/RestAssured.Net/3.0.0-beta.cookies) and see if you can extract the `Auth` cookie value like this?

```csharp
[Test]
public void HttpOnlySecureCookieValueCanBeExtracted()
{
    string authCookieValue = Given()
        .When()
        .Get($"{MOCK_SERVER_BASE_URL}/response-with-httponly-secure-cookie")
        .Then()
        .StatusCode(200)
        .And()
        .Extract().Cookie("Auth");

    Assert.That(authCookieValue, Is.EqualTo("123"));
}
```

Please let me know if that works for you and if not, what the response is you're seeing.

**Comment by workmichsem** [comment] 2023-07-04 04:13
Have a question
How this work in 3.0.0-beta.cookies version?
I highlighted the methods that are now missing.

RequestSpecification Spec = new RequestSpecBuilder()
        .WithRequestLogLevel(RequestLogLevel.All)
        **.WithRelaxedHttpsValidation()**
        .WithScheme("https")
        .WithHostName("HostName")
        .Build();

var json = ClientV1
            .Get(token, jsonForSend)
            .Log(ResponseLogLevel.All)
            .StatusCode(200)
            .Extract()**.As(typeof(SuccessResponseModel));**

**Comment by basdijkstra** [comment] 2023-07-04 05:02
Those methods you highlighted were deprecated and have now been removed indeed.

You can replace .WithRelaxedHttpsValidation() with .DisableSslCertificateValidation() and .As() with .DeserializeTo()

I’ve made these changes because of readability. The way they work remains the same.

**Comment by workmichsem** [comment] 2023-07-04 06:46
Hurrah, it works!

Would it be possible to add the output of such cookies to Log(ResponseLogLevel.All) ?

It's not necessary for me, but it would be perfect.

**Comment by basdijkstra** [comment] 2023-07-04 07:52
Ah that's great news!

Yes, logging cookies is entirely possible, quite easily even now that this works. What I'll be adding:

* Methods to verify cookie values
* Logging cookies as part of `Log(ResponseLogLevel.All)`
* More tests, especially around multi-value cookies

I also want to build something that enables the user to replace the value of a cookie (and a header) with something like `*****` when logging, to enable 'more secure' logging, but that's going to be a different story and probably not part of the 3.0.0 release.

Anything else you think I should add? If not I'll get to work on this. Should not take me too long.

**Comment by workmichsem** [comment] 2023-07-04 08:22
For me this is completely enough.

Thank you very much for responding quickly and improving the library as always!

**Comment by basdijkstra** [comment] 2023-07-04 09:25
All added. This is what's logged now (as an example) when you using `ResponseLogLevel.All` or `ResponseLogLevel.Headers`:

`Cookie: Auth=123, Domain: localhost, HTTP-only: True, Secure: True`

All this will be included in the 3.0.0 release which I think will go live today or tomorrow.

Thank you again for your patience, @workmichsem, it took me a while to figure out what you meant but in the end, the library has improved because of it. Thank you so much for your support.

Please test this with the proper 3.0.0 release and close the issue when you think all is OK.

**Comment by basdijkstra** [comment] 2023-07-04 13:05
@workmichsem, version 3.0.0 is live: https://www.nuget.org/packages/RestAssured.Net/3.0.0

**Comment by workmichsem** [comment] 2023-07-07 06:01
Sorry for the long reply

I tried it works
Thanks a lot!

**Comment by basdijkstra** [comment] 2023-07-07 06:05
No problem, thank you for the feedback, @workmichsem. Closing this issue.

**Closed by basdijkstra** 2023-07-07 06:05 UTC
Labels: bug, waiting for feedback
