### ISSUE TITLE
Cannot send Post request without character encoding

### ISSUE THREAD

**Issue by karboncopy** [basdijkstra/rest-assured-net#132] opened 2024-12-01 16:44 UTC
When sending a POST request to an endpoint, the character encoding of the request is utf-8 by default and there is no way to not encode the request body
The following test always sends a request with a default encoding if the test does not mention a different encoding.
In some situations, the server only accepts requests of raw json, in which case, the test fails. Even if there is no actual issue with the API.

`
    public class WeatherForecastTests
    {
        LogConfiguration _logConfig;

        public WeatherForecastTests()
        {

            _logConfig = new LogConfiguration
            {
                RequestLogLevel = RequestLogLevel.All,
                ResponseLogLevel = ResponseLogLevel.All,
            };
        }

        [Fact]
        public void ShouldPostWeatherForecast()
        {
            string requestBody = $@"{{
                              ""Name"":""Stormy"",
                              ""TemperatureF"": 157
                            }}";

            Given()
                .Log(_logConfig)
                .ContentType("application/json")
                .Body(requestBody)
                .Post("https://localhost:7223/weatherforecast")
                .StatusCode(200);
        }
    }
}`

I've created a small repo demonstrating the issue [here](https://github.com/karboncopy/RestAssuredNET.Issue)

**Comment by basdijkstra** [comment] 2024-12-01 17:41
Hey @karboncopy, thank you for filing this issue, and I really appreciate the repro repo :)

I’ll try and have a look later this week.

**Comment by basdijkstra** [comment] 2024-12-02 12:02
Hi @karboncopy, if I clone your repo and import it into VS, I get errors. Also, I can't see the tests themselves?

**Comment by karboncopy** [comment] 2024-12-02 17:44
Sorry for that, @basdijkstra  I have created a new repo https://github.com/karboncopy/RestAssuredNET.Issue

Thank you

**Comment by basdijkstra** [comment] 2024-12-02 18:17
No worries! Thanks, I’ll have a quick look tomorrow morning.

**Comment by basdijkstra** [comment] 2024-12-05 16:20
@karboncopy I can confirm I see the same issue. `Content-Type` is automatically set to `application/json; charset=utf-8` on serialization.

If I change the service implementation to contain `!context.Request.ContentType.Contains("application/json")` it does accept the request but that's not the solution you're looking for ;)

I'll see what I can do to fix this soon. Need to find a bit of time to dive into the encoding process. Will keep you posted.

**Comment by karboncopy** [comment] 2024-12-06 08:51
Thank you :)

**Comment by basdijkstra** [comment] 2024-12-08 08:21
Hmm.. This is an interesting case. As you can see here, the default encoding I set is UTF-8:

https://github.com/basdijkstra/rest-assured-net/blob/ec190a69cd4916019df5530d90e39700036b6baf/RestAssured.Net/Request/ExecutableRequest.cs#L51

which is then used when creating the `StringContent` request payload here: https://github.com/basdijkstra/rest-assured-net/blob/ec190a69cd4916019df5530d90e39700036b6baf/RestAssured.Net/Request/ExecutableRequest.cs#L798

When I set the default to another value, the `StringContent` constructor respects that and adds, for example, `; charset=iso-8859-1` to the `Content-Type` header when I set the encoding to `Encoding.Latin1`.

When I set the default value to `null`, the content type goes into the `StringContent` constructor as `null`, but, and this is important, it **comes out as** `; charset=utf=8`. In other words, when we don't specify the encoding explicitly, the `StringContent` class (see Microsoft docs [here](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.stringcontent)) defaults to UTF-8.

Now, there seems to be a bit of a debate going on about whether the `charset` is needed. The [official spec](https://www.rfc-editor.org/rfc/rfc8259#section-11) says that you shouldn't have to add a `charset`:

> "Note:  No "charset" parameter is defined for this registration. Adding one really has no effect on compliant recipients."

But that only applies to JSON. Remember, both `System.Net.Http` and RestAssured .NET are multipurpose, and while JSON is no doubt the data format most often used, I can't simply change the default behaviour by setting the default to `null` and removing it when users haven't explicitly specified a character encoding. I have no idea what the fallout of that would be.

Also, adding a charset seems recommended for specific cases, even when the official spec says it's useless. See [this blog post](https://www.hanselman.com/blog/why-the-askobama-tweet-was-garbled-on-screen-know-your-utf8-unicode-ascii-and-ansi-decoding-mr-president) for an example.

What I **can** do is add a second, optional parameter to `Body()` that allows you to strip the charset from the resulting `Content-Type` header after the `StringContent` is created. For now, that's a simple boolean flag, defaulting to `false`.

I've added that option to RestAssured .NET version 4.6.0-beta.1, which I have just published. Will test it with your repro project in a few minutes.

I would have liked to deprecate the `ContentEncoding()` method and pass in the `Encoding` as a second, optional parameter to the `Body()` instead, but I can't supply `Encoding.UTF8` as a default because it's not a compile-time constant and null isn't a useful default value for the reasons I mentioned above.

**Comment by basdijkstra** [comment] 2024-12-08 08:25
@karboncopy I tested my solution with the new RestAssured .NET 4.6.0 beta and your reproduction repo, and it seems to work now.

Can you please test on your side, too, and let me know if it works for your _real_ project? If so, I'll release a proper `4.6.0` version right away.

**Comment by karboncopy** [comment] 2024-12-08 09:16
Have retested with the actual project and now the test passes. Thank you for taking the time to look into this. I really appreciate it.

**Comment by basdijkstra** [comment] 2024-12-08 09:18
Thank _you_ for the quick testing, on a Sunday no less :) I’ll release a proper `4.6.0` version early this week and will then close this issue.

**Comment by basdijkstra** [comment] 2024-12-09 11:37
RestAssured .Net 4.6.0 [is now live](https://www.nuget.org/packages/RestAssured.Net/4.6.0), so I'm closing this issue.

Thanks again for reporting it and for the collaboration and testing, @karboncopy!

**Closed by basdijkstra** 2024-12-09 11:37 UTC
Labels: bug
